mode: predict
debug: False
load_ckpt: experiments/spcfgfncvm002ema_spcf/checkpoint_best_ema0995.pkl
components:
  data: predict_local2
  transform: spcf
  system: spcfgfncvm002_spcf
  model: spcfgfncvm002a105_spcf
writer:
  __target__: vm
  save_dir: results_local2_fncvm002ema0995_a105
  save_name: denoised
