mode: predict
debug: False
load_ckpt: experiments/spcfgfnpnx001_spcf/checkpoint_best.pkl
components:
  data: predict
  transform: spcf
  system: spcfgfnpnx001_spcf
  model: spcfgfnpnx001a105_spcf
writer:
  __target__: vm
  save_dir: submission_results/pnx001_a105_raw_20260720
  save_name: denoised
