mode: predict
debug: False
load_ckpt: experiments/spcfgfnuni001_spcf/checkpoint_best.pkl
components:
  data: predict_local2
  transform: spcf
  system: spcfgfnuni001_spcf
  model: spcfgfnuni001a105_spcf
writer:
  __target__: vm
  save_dir: results_local2_spcfgfnuni001a105
  save_name: denoised
