mode: predict
debug: False
load_ckpt: experiments/spcfgfnrot001_spcf/checkpoint_best.pkl
components:
  data: predict_local2
  transform: spcf
  system: spcfgfnrot001_spcf
  model: spcfgfncvm002a105_spcf
writer:
  __target__: vm
  save_dir: results_local2_spcfgfnrot001a105
  save_name: denoised
