mode: predict
debug: False
load_ckpt: experiments/spcfgfncvm002ema_spcf/checkpoint_best.pkl
components:
  data: predict_submit_ema_raw_s0
  transform: spcf
  system: spcfgfncvm002_spcf
  model: spcfgfncvm002a105_spcf
writer:
  __target__: vm
  save_dir: submission_results/ema_raw_submit
  save_name: denoised
