mode: predict
debug: False
load_ckpt: experiments/spcfgfncond001_spcf/checkpoint_best.pkl
components:
  data: predict_local2
  transform: spcf
  system: spcfgfncond001_spcf
  model: spcfgfncond001a105_spcf
writer:
  __target__: vm
  save_dir: results_local2_spcfgfncond001a105
  save_name: denoised
