mode: predict
debug: False
load_ckpt: experiments/spcfgfnldc_spcf/checkpoint_best.pkl
components:
  data: predict
  transform: spcf
  system: spcfgfnldc_spcf
  model: spcfgfnldc_spcf
writer:
  __target__: vm
  save_dir: submission_results/ldc_spcfgfnldc
  save_name: denoised
