mode: predict
debug: False
load_ckpt: experiments/spcfgfncvm002_spcf/checkpoint_best.pkl
components:
  data: predict
  transform: spcf
  system: spcfgfncvm002_spcf
  model: spcfgfncvm002_spcf
writer:
  __target__: vm
  save_dir: submission_results/cvm002_spcfgfncvm002
  save_name: denoised
