mode: predict
debug: False
load_ckpt: experiments/spcfgfncvm002_spcf/checkpoint_best.pkl
components:
  data: predict_local3
  transform: spcf
  system: spcfgfncvm002_spcf
  model: spcfgfncvm002a105_spcf
writer:
  __target__: vm
  save_dir: results_local3_fncvm002a105
  save_name: denoised
