mode: predict
debug: False
load_ckpt: experiments/spcfgfncvm002seed456_spcf/checkpoint_best.pkl
components:
  data: predict_local2
  transform: spcf
  system: spcfgfncvm002_spcf
  model: spcfgfncvm002a105_spcf
writer:
  __target__: vm
  save_dir: results_local2_fncvm002seed456_a105
  save_name: denoised
