mode: predict
debug: False
load_ckpt: experiments/spcf_spcf/checkpoint_best.pkl
components:
  data: predict_local
  transform: spcf
  system: spcf_spcf
  model: spcf_spcf
writer:
  __target__: vm
  save_dir: results_local
  save_name: denoised
