mode: predict
debug: False
load_ckpt: experiments/spcfg_spcf/checkpoint_best.pkl
components:
  data: predict_local
  transform: spcf
  system: spcfg_spcf
  model: spcfg_spcf
writer:
  __target__: vm
  save_dir: results_local
  save_name: denoised
