mode: predict
debug: False
load_ckpt: experiments/spcfgfnrot001_spcf/checkpoint_best.pkl
components:
  data: predict
  transform: spcf
  system: spcfgfnrot001_spcf
  model: spcfgfncvm002a105_spcf
writer:
  __target__: vm
  save_dir: submission_results/rot001_a105_raw_20260719
  save_name: denoised
