mode: predict
debug: False
load_ckpt: experiments/spcfgfnldc_spcf/checkpoint_best.pkl
components:
  data: predict_local2
  transform: spcf
  system: spcfgfnldc_spcf
  model: spcfgfnldc_spcf
writer:
  __target__: vm
  save_dir: results_local2_fnldc
  save_name: denoised
