mode: train
debug: False
init_stage_ckpt: experiments/_bak_official_75.01/cvm_checkpoint_best.pkl
components:
  data: spcf_train_pd002
  transform: spcf_n_rot001
  system: spcfgfnpnx001_cvm
  model: spcfgfnpnx001_cvm
loss:
  loss: 1.0
optimizer:
  __target__: adam
  lr: 0.00003
trainer:
  epochs: 120
  save_best_only: True
  early_stopping:
    enabled: True
    monitor: val/loss_sum
    mode: min
    patience: 20
    min_delta: 0.0000005
