mode: train
debug: False

components:
  data: train
  transform: vm
  system: vm
  model: vm

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.00001

trainer:
  epochs: 100
  save_best_only: True
  early_stopping:
    enabled: True
    monitor: val/loss_sum
    mode: min
    patience: 10
    min_delta: 0.000001
