mode: train
debug: False
init_stage_ckpt: experiments/spcfg_cvm/checkpoint_best.pkl
components:
  data: spcf_train
  transform: spcf
  system: spcfg_spcf
  model: spcfg_spcf
loss:
  loss: 1.0
optimizer:
  __target__: adam
  lr: 0.0001
trainer:
  epochs: 100
  save_best_only: True
  early_stopping:
    enabled: True
    monitor: val/loss_sum
    mode: min
    patience: 15
    min_delta: 0.0000005
